spring:
  application:
    name: profile-prod
  profiles:    active:    - prod
#server:#  port: 9191

security:  oauth2:    resource:      token-info-uri: http://localhost:7070/oauth/check_token
    client:      client-id: mobile
      client-secret: pin