server:
  port: 7070
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: Sohrab@78692
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace